(cl:defpackage deepracer_simulation-srv
  (:use )
  (:export
   "GETWAYPOINTSRV"
   "<GETWAYPOINTSRV-REQUEST>"
   "GETWAYPOINTSRV-REQUEST"
   "<GETWAYPOINTSRV-RESPONSE>"
   "GETWAYPOINTSRV-RESPONSE"
   "RESETCARSRV"
   "<RESETCARSRV-REQUEST>"
   "RESETCARSRV-REQUEST"
   "<RESETCARSRV-RESPONSE>"
   "RESETCARSRV-RESPONSE"
  ))

